-- =============================================================================
-- CineBook Database Schema
-- Phase 3 - Milestone 1
-- PostgreSQL 15+
-- =============================================================================

-- Enable the pgcrypto extension for password hashing (used by application layer)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- TABLES
-- =============================================================================

-- Users: both customers and administrators
CREATE TABLE IF NOT EXISTS Users (
    UserID       SERIAL PRIMARY KEY,
    Name         VARCHAR(100)  NOT NULL,
    Email        VARCHAR(255)  NOT NULL UNIQUE,
    Password     VARCHAR(255)  NOT NULL,  -- bcrypt hash; never store plain text
    Role         VARCHAR(20)   NOT NULL DEFAULT 'customer'
                     CHECK (Role IN ('customer', 'admin')),
    FavoriteGenre VARCHAR(50),
    LoyaltyPoints INTEGER       NOT NULL DEFAULT 0 CHECK (LoyaltyPoints >= 0),
    CreatedAt    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- Theaters: physical screening rooms (Hall A, IMAX Screen, etc.)
CREATE TABLE IF NOT EXISTS Theaters (
    TheaterID     SERIAL PRIMARY KEY,
    Name          VARCHAR(100) NOT NULL,
    Location      VARCHAR(255) NOT NULL,
    TotalCapacity INTEGER      NOT NULL CHECK (TotalCapacity > 0),
    ScreenType    VARCHAR(50)  NOT NULL DEFAULT 'Standard'
                      CHECK (ScreenType IN ('Standard', 'IMAX', 'Dolby', '4DX'))
);

-- Movies: catalog of films shown at the theater
CREATE TABLE IF NOT EXISTS Movies (
    MovieID      SERIAL PRIMARY KEY,
    Title        VARCHAR(255) NOT NULL,
    Genre        VARCHAR(100) NOT NULL,
    Duration     INTEGER      NOT NULL CHECK (Duration > 0),  -- minutes
    ReleaseDate  DATE,
    TMDB_ID      INTEGER      UNIQUE,                         -- foreign key to TMDB
    Description  TEXT,
    PosterURL    VARCHAR(500)
);

-- External_Metadata: live TMDB data linked to Movies; updated by cron job
CREATE TABLE IF NOT EXISTS External_Metadata (
    MetadataID      SERIAL PRIMARY KEY,
    MovieID         INTEGER        NOT NULL
                        REFERENCES Movies(MovieID) ON DELETE CASCADE,
    TMDB_Popularity NUMERIC(10, 3) CHECK (TMDB_Popularity >= 0),
    TMDB_Rating     NUMERIC(3, 1)  CHECK (TMDB_Rating BETWEEN 0 AND 10),
    TrendingStatus  VARCHAR(20)    NOT NULL DEFAULT 'normal'
                        CHECK (TrendingStatus IN ('trending', 'normal', 'declining')),
    LastUpdated     TIMESTAMP      NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_movie_metadata UNIQUE (MovieID)
);

-- Showtimes: a specific screening of a movie in a theater on a given date/time
CREATE TABLE IF NOT EXISTS Showtimes (
    ShowtimeID       SERIAL PRIMARY KEY,
    MovieID          INTEGER        NOT NULL REFERENCES Movies(MovieID)   ON DELETE CASCADE,
    TheaterID        INTEGER        NOT NULL REFERENCES Theaters(TheaterID) ON DELETE CASCADE,
    StartTime        TIME           NOT NULL,
    Date             DATE           NOT NULL,
    BasePrice        NUMERIC(8, 2)  NOT NULL CHECK (BasePrice > 0),
    CurrentOccupancy INTEGER        NOT NULL DEFAULT 0 CHECK (CurrentOccupancy >= 0),
    CONSTRAINT unique_theater_slot UNIQUE (TheaterID, Date, StartTime)
);

-- Bookings: one row per seat reserved by a user for a specific showtime
CREATE TABLE IF NOT EXISTS Bookings (
    BookingID   SERIAL PRIMARY KEY,
    UserID      INTEGER       NOT NULL REFERENCES Users(UserID)     ON DELETE CASCADE,
    ShowtimeID  INTEGER       NOT NULL REFERENCES Showtimes(ShowtimeID) ON DELETE CASCADE,
    SeatNumber  VARCHAR(10)   NOT NULL,
    BookingTime TIMESTAMP     NOT NULL DEFAULT NOW(),
    FinalPrice  NUMERIC(8, 2) NOT NULL CHECK (FinalPrice > 0),
    Status      VARCHAR(20)   NOT NULL DEFAULT 'confirmed'
                    CHECK (Status IN ('confirmed', 'cancelled', 'pending')),
    CONSTRAINT unique_seat_per_showtime UNIQUE (ShowtimeID, SeatNumber)
);

-- Demand_Forecasts: admin-facing predictive data generated by the forecasting engine
CREATE TABLE IF NOT EXISTS Demand_Forecasts (
    ForecastID          SERIAL PRIMARY KEY,
    ShowtimeID          INTEGER       NOT NULL
                            REFERENCES Showtimes(ShowtimeID) ON DELETE CASCADE,
    PredictedOccupancy  NUMERIC(5, 2) CHECK (PredictedOccupancy BETWEEN 0 AND 100),
    PredictedRevenue    NUMERIC(12, 2),
    RecommendationLevel VARCHAR(20)   NOT NULL DEFAULT 'normal'
                            CHECK (RecommendationLevel IN ('add_screening', 'adjust_price',
                                                           'high_demand', 'normal')),
    GeneratedAt         TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- INDEXES
-- (Primary keys are indexed automatically; these cover common query patterns)
-- =============================================================================

-- Movie catalog lookups by genre and title
CREATE INDEX IF NOT EXISTS idx_movies_genre   ON Movies(Genre);
CREATE INDEX IF NOT EXISTS idx_movies_title   ON Movies(Title);
CREATE INDEX IF NOT EXISTS idx_movies_tmdb_id ON Movies(TMDB_ID);

-- Showtime lookups by date and movie
CREATE INDEX IF NOT EXISTS idx_showtimes_date     ON Showtimes(Date);
CREATE INDEX IF NOT EXISTS idx_showtimes_movie_id ON Showtimes(MovieID);

-- Booking lookups per user
CREATE INDEX IF NOT EXISTS idx_bookings_user_id     ON Bookings(UserID);
CREATE INDEX IF NOT EXISTS idx_bookings_showtime_id ON Bookings(ShowtimeID);
CREATE INDEX IF NOT EXISTS idx_bookings_status      ON Bookings(Status);

-- Forecast lookups by showtime
CREATE INDEX IF NOT EXISTS idx_forecasts_showtime_id ON Demand_Forecasts(ShowtimeID);

-- Metadata freshness check
CREATE INDEX IF NOT EXISTS idx_metadata_last_updated ON External_Metadata(LastUpdated);

-- =============================================================================
-- TRIGGER: keep CurrentOccupancy in sync with Bookings
-- The backend can also do this, but a DB-level trigger is the safety net.
-- =============================================================================

CREATE OR REPLACE FUNCTION update_occupancy()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.Status = 'confirmed' THEN
        UPDATE Showtimes
        SET    CurrentOccupancy = CurrentOccupancy + 1
        WHERE  ShowtimeID = NEW.ShowtimeID;

    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.Status != 'cancelled' AND NEW.Status = 'cancelled' THEN
            UPDATE Showtimes
            SET    CurrentOccupancy = GREATEST(CurrentOccupancy - 1, 0)
            WHERE  ShowtimeID = NEW.ShowtimeID;
        ELSIF OLD.Status = 'cancelled' AND NEW.Status = 'confirmed' THEN
            UPDATE Showtimes
            SET    CurrentOccupancy = CurrentOccupancy + 1
            WHERE  ShowtimeID = NEW.ShowtimeID;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_update_occupancy ON Bookings;
CREATE TRIGGER trg_update_occupancy
AFTER INSERT OR UPDATE OF Status ON Bookings
FOR EACH ROW EXECUTE FUNCTION update_occupancy();
